### ISSUE TITLE
Can't use CDATA

### ISSUE THREAD

**Issue by ray1984** [tomj74/chunk-templates#16] opened 2016-02-27 21:54 UTC
I have a troubles when I set expression like this `Cucumber<br>`in xml like that `<p>{$item.name}</p>`. In that case I receive invalid xml - `<p>Cucumber<br></p>`. 
I tryed change xml-pattern to `<p><![CDATA[{$item.name}]]><p>`. But in that case I receive weird result:
`<p><!--[CDATA[Cucumber<br>]]--></p>`
Why do you comment CDATA? Can you offer me some workaround?

**Comment by tomj74** [comment] 2016-02-29 05:23
As a quick workaround, you should be able to use &lt; and &gt; in place of the angle brackets and they will be rendered properly.  CDATA support is likely to be pretty hacky/brittle but I'll look into it.

**Comment by ray1984** [comment] 2016-02-29 08:12
Well, I set objects to chunk. I wouldn't like to change objects

**Comment by tomj74** [comment] 2016-02-29 15:37
Oh, I misunderstood the question.  I think what you really want is to escape the value properly?  There are template filters that exist for exactly this purpose:

    <p>{$item.name|xmlescape}</p>

This can be abbreviated to just:

    <p>{$item.name|xml}</p>

**Comment by tomj74** [comment] 2016-03-02 00:53
As far as the comment tags go, I am unable to reproduce the behavior you are seeing.  Can you attach a simple case of template and java code that produces the mysterious commenting?

**Comment by tomj74** [comment] 2016-03-04 18:43
closing for now, will reopen if reproducible case is submitted.

**Closed by tomj74** 2016-03-04 18:43 UTC
